services:
    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1122
          POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        networks:
            - my_network
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - my_network
    app:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - redis
            - postgres
        networks:
            - my_network

networks:
    my_network:
